program: train_od.py
method: bayes
metric:
  name: eval/loss
  goal: minimize

# The hyperparameters to sweep over
parameters:
  train-lr:
    min: 0.000001
    max: 0.0001
  train-batch_size:
    values: [8, 16, 32, 64]
  train-weight_decay:
    min: 0.000001
    max: 0.0001
  pmodel-rank:
    values: [2, 4, 8, 16, 32, 64]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - "override=True"
  - "pmodel.method=loraconv2d"

# python train_od.py pmodel.method=loraconv2d pmodel.rank=4