program: train_od.py
method: bayes
metric:
  name: "eval/AP-IoU=0.50-area=all-maxDets=100"
  goal: maximize

# The hyperparameters to sweep over
parameters:
  train-lr:
    values: [0.0005, 0.0001, 0.00005, 0.00001, 0.000005, 0.000001 ]
  pmodel-rank:
    values: [ 2, 4, 8, 16, 32, 64 ]
  pmodel-ignore_regex:
    values:
      - '.*model\.backbone\.conv_encoder\.model\.layer1.*|.*model\.backbone\.conv_encoder\.model\.conv1.*'
      - '.*model\.backbone\.conv_encoder\.model\.conv1.*'

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - "override=True"
  - "pmodel.method=loraconv2d"
  - "train.epochs=5"

# python train_od.py pmodel.method=loraconv2d pmodel.rank=4