program: train_od.py
method: bayes
metric:
  name: eval/loss
  goal: minimize

# The hyperparameters to sweep over
parameters:
  train-lr:
    values: [0.001, 0.0001, 0.00001, 0.000001]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - "override=True"
  - "pmodel.method=none"
  - "train.epochs=5"

# python train_od.py pmodel.method=loraconv2d pmodel.rank=4